---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BOJOS PER LA BIOMEDICINA 2024

All species on Earth are under constant change. Over generations, the DNA molecules of individuals within a population will undergo random changes (termed mutations), and this can sometimes translate to alterations in their biology, such as the emergence of a new trait (like resistance to a given antibiotic, or a colour that helps them camouflage better). If this trait is advantageous, individuals carrying the mutation will survive better and reproduce more than their counterparts, influencing the genetic makeup of the population. With time, this can result in a whole new species and it is the basis underlying the extraordinary biodiversity present on the planet.

DNA sequencing allows us to keep track of the emergence of these mutations across individuals and link them to the changes we can see in the clinic. By analyzing the similarities and differences in these sequences at a large scale (which we call comparative genomics), we can reconstruct the relationship between the populations or species carrying them, and understand how new traits appear and evolve. For example, this field of science proved very useful during the COVID-19 pandemic as it allowed researchers to monitor the emergence of new variants of SARS-CoV-2 and their spread across different countries almost in real-time, as well as develop vaccines that targeted proteins that were less prone to change.

In this course, students will apply a computational (dry lab) perspective to the understanding of the evolution of pathogenic agents. In particular, students will track the emergence of a new human virus from an animal pathogen and examine the changes that have allowed it to make the jump from one host to another, and we will gain an understanding of where it originated and how it spread. Students will learn how computers can be a powerful tool in a researcher's toolkit for understanding infectious diseases, predicting outbreaks, and designing therapeutic strategies.
